file(MAKE_DIRECTORY "${WORK}" "${PACKAGE}/Artifacts" "${PACKAGE}/LyraCore/Resources/Licenses")
set(archive "${WORK}/libCLyraCore.a")
execute_process(
  COMMAND "${XCRUN}" libtool -static -o "${archive}" "${CORE}" "${IDENTITY}" "${MLX}" "${JACCL}"
  COMMAND_ERROR_IS_FATAL ANY)
set(framework "${PACKAGE}/Artifacts/CLyraCore.xcframework")
file(REMOVE_RECURSE "${framework}")
execute_process(
  COMMAND "${XCRUN}" xcodebuild -create-xcframework -library "${archive}"
          -headers "${HEADERS}" -output "${framework}"
  COMMAND_ERROR_IS_FATAL ANY)
file(COPY_FILE "${METALLIB}" "${PACKAGE}/LyraCore/Resources/mlx.metallib" ONLY_IF_DIFFERENT)
file(COPY_FILE "${ROOT}/LICENSE" "${PACKAGE}/LyraCore/Resources/Licenses/LYRA-APACHE-2.0.txt" ONLY_IF_DIFFERENT)
file(COPY_FILE "${MLX_LICENSE}" "${PACKAGE}/LyraCore/Resources/Licenses/MLX-MIT.txt" ONLY_IF_DIFFERENT)
file(COPY "${ROOT}/native/licenses/" DESTINATION "${PACKAGE}/LyraCore/Resources/Licenses")
file(COPY_FILE "${ROOT}/vendor/yue/THIRD_PARTY_NOTICES.md"
     "${PACKAGE}/LyraCore/Resources/Licenses/YUE-THIRD-PARTY-NOTICES.txt" ONLY_IF_DIFFERENT)
file(COPY "${ROOT}/vendor/yue/licenses/" DESTINATION "${PACKAGE}/LyraCore/Resources/Licenses")
# A changed native archive must invalidate the Swift object/link action, not
# only SwiftPM's binary-copy action. The runtime also verifies this pairing.
file(READ "${BUILD_ID}" identity)
file(CONFIGURE OUTPUT "${PACKAGE}/LyraCore/NativeBuild.swift" CONTENT
  "// Generated by lyra_swift_package. Do not edit.\nlet packagedCoreBuildIdentifier = \"${identity}\"\n"
  @ONLY)
